version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: LeagueCoreService/Dockerfile
    container_name: LeagueService
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__PostgreSQL: ${DB_CONNECTION}
      Leago__ClientId: ${LEAGO_ID}
      Leago__ClientSecret: ${LEAGO_SECRET}
      Discord__AppId: ${DISCORD_APPID}
      Discord__PublicKey: ${DISCORD_PUBLICKEY}
      Discord__Token: ${DISCORD_TOKEN}
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet: