//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discord {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DiscordTemplates {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiscordTemplates() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Discord.DiscordTemplates", typeof(DiscordTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string UpcomingMatchesIntroMessage {
            get {
                return ResourceManager.GetString("UpcomingMatchesIntroMessage", resourceCulture);
            }
        }
        
        internal static string RoundStartMessage {
            get {
                return ResourceManager.GetString("RoundStartMessage", resourceCulture);
            }
        }
        
        internal static string ReviewScheduleMessage {
            get {
                return ResourceManager.GetString("ReviewScheduleMessage", resourceCulture);
            }
        }
        
        internal static string ReviewEventNoticeMessage {
            get {
                return ResourceManager.GetString("ReviewEventNoticeMessage", resourceCulture);
            }
        }
        
        internal static string ReviewEventBodyMessage {
            get {
                return ResourceManager.GetString("ReviewEventBodyMessage", resourceCulture);
            }
        }
        
        internal static string ReviewThreadMessage {
            get {
                return ResourceManager.GetString("ReviewThreadMessage", resourceCulture);
            }
        }
    }
}
